version: '2'
services:
  bitbucket:
    image: atlassian/bitbucket-server:5.3
    restart: always
    ports:
      - 7990:7990
    volumes:
      - ./bitbucket:/var/atlassian/application-data/bitbucket
