version: '2'
services:
  gitlab:
    container_name: gitlab
    image: gitlab/gitlab-ce:latest
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./gitlab/data:/var/opt/gitlab
      - ./gitlab/config:/etc/gitlab
