version: '2'
services:
  grafana:
    container_name: grafana
    image: grafana/grafana:6.3.6
    restart: always
    environment:
      GF_AUTH_PROXY_ENABLED: 'true'
      GF_AUTH_ANONYMOUS_ENABLED: 'true'
    ports:
      - 3000:3000
    volumes:
      - ./grafana:/var/lib/grafana
