version: '2'
services:
  mockserver:
    image: mockserver/mockserver
    container_name: mockserver
    ports:
      - 1080:1080
    environment:
      LOG_LEVEL: "DEBUG"
      SERVER_PORT: 1080
#      MOCKSERVER_INITIALIZATION_JSON_PATH: /config/initializerJson.json
#    volumes:
#      - ./initializerJson.json:/config/initializerJson.json
