version: "3"
services: 
  sq-postgres:
    container_name: sq-postgres
    image: postgres:10
    restart: always
    volumes:
      - /workspace/sq-postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=sonar
      - POSTGRES_PASSWORD=sonar
  sq-sonarqube:
    container_name: sq-sonarqube
    image: sonarqube:7.9-community
    restart: always
    ports:
      - "9000:9000"
    environment:
      - SONARQUBE_JDBC_URL=jdbc:postgresql://sq-postgres:5432/sonar
