version: '2'
services:
   mariadb:
     image: bitnami/mariadb:latest
     environment:
       - MARIADB_USER=bn_testlink
       - MARIADB_DATABASE=bitnami_testlink
       - ALLOW_EMPTY_PASSWORD=yes
     volumes:
       - /workspace/mariadb_data:/bitnami

   testlink:
     image: bitnami/testlink:1
     environment:
       - MARIADB_HOST=mariadb
       - MARIADB_PORT_NUMBER=3306
       - TESTLINK_DATABASE_USER=bn_testlink
       - TESTLINK_DATABASE_NAME=bitnami_testlink
       - ALLOW_EMPTY_PASSWORD=yes
       - TESTLINK_USERNAME=admin
       - TESTLINK_PASSWORD=baoxian-sz
       - TESTLINK_EMAIL=shiwei@baoxian-sz.com
     ports:
       - 80:80
       - 443:443
     volumes:
       - /workspace/testlink_data:/bitnami
     depends_on:
       - mariadb
