version: '2'
services:
   tl-mariadb:
     container_name: tl-mariadb
     image: bitnami/mariadb:latest
     environment:
       - MARIADB_USER=tl_testlink
       - MARIADB_DATABASE=tl_testlink
       - ALLOW_EMPTY_PASSWORD=yes
     volumes:
       - /workspace/testlink/mariadb_data:/bitnami

   tl-testlink:
     container_name: tl-testlink
     image: bitnami/testlink:1
     environment:
       - MARIADB_HOST=tl-mariadb
       - MARIADB_PORT_NUMBER=3306
       - TESTLINK_DATABASE_USER=tl_testlink
       - TESTLINK_DATABASE_NAME=tl_testlink
       - ALLOW_EMPTY_PASSWORD=yes
       - TESTLINK_USERNAME=will
       - TESTLINK_PASSWORD=baoxian-sz
       - TESTLINK_EMAIL=shiwei@baoxian-sz.com
     ports:
       - 80:80
       - 443:443
     volumes:
       - /workspace/testlink/testlink_data:/bitnami
     depends_on:
       - tl-mariadb
