# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: "撩保星球 - Assurance Sphere - 石巍的个人主页"
email: service@bowxeon.com
description: >- # this means to ignore newlines until "baseurl:"
  Assurance Sphere - Will's workspace
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://will.bowxeon.com" # the base hostname & protocol for your site, e.g. http://example.com
github_username: seoktaehyeon

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

timezone: Asia/Shanghai

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
  - .gitignore
  - .github
  - Gemfile
  - Dockerfile
# EXCLUDE_IN_DOCKER  - assets/css/
# EXCLUDE_IN_DOCKER  - assets/js/
# EXCLUDE_IN_DOCKER  - assets/img/
# EXCLUDE_IN_DOCKER  - assets/posts/
  - assets/fonts  # EXCLUDE_IN_GITEE_PAGES
  - _layouts      # EXCLUDE_IN_GITEE_PAGES
  - _includes     # EXCLUDE_IN_GITEE_PAGES
  - index.md      # EXCLUDE_IN_GITEE_PAGES
  - pagetree.json # EXCLUDE_IN_GITEE_PAGES
  - 404.md        # EXCLUDE_IN_GITEE_PAGES
  - search.md     # EXCLUDE_IN_GITEE_PAGES
  - search.json   # EXCLUDE_IN_GITEE_PAGES
  - sqa/          # EXCLUDE_IN_GITEE_PAGES
  - devops/       # EXCLUDE_IN_GITEE_PAGES
  - workspace/    # EXCLUDE_IN_GITEE_PAGES
  - health/       # EXCLUDE_IN_GITEE_PAGES
  - author/       # EXCLUDE_IN_GITEE_PAGES

path:
 css: "//vstone.gitee.io/workspace/assets/css"
 js: "//vstone.gitee.io/workspace/assets/js"
 img: "//vstone.gitee.io/workspace/assets/img"
 posts: "//vstone.gitee.io/workspace/assets/posts"
 fonts: "//will.bowxeon.com/assets/fonts"
 logo: 
   favicon: "//vstone.gitee.io/workspace/assets/img/logo.png"
   header: "//vstone.gitee.io/workspace/assets/img/logo_white.svg"
   footer: "//vstone.gitee.io/workspace/assets/img/logo.svg"

theme_color_header: "#395ca3"
theme_color_footer: "#f0f0f0"
theme_color_footer_text: "#70757a"

nav:
  - title: "首页"
    id: null
    url: "/"
    target: ""
  - title: "软件质量保障"
    id: sqa
    url: "/sqa"
    target: ""
  - title: "DevOps"
    id: devops
    url: "/devops"
    target: ""
  - title: "工作随笔"
    id: workspace
    url: "/workspace"
    target: ""
  - title: "健康菜单"
    id: health
    url: "/health?p=day"
    target: ""

my_projects:
  - name: QSphere质量数据平台
    url: "https://qualitysphere.gitee.io/"
  - name: OpenDevOps
    url: "https://qualitysphere.gitee.io/ext/odo/"
  - name: Allure框架中文手册
    url: "https://qualitysphere.gitee.io/ext/allure/"
  - name: PyPi WorkWeixinRobot
    url: "https://pypi.org/project/WorkWeixinRobot/"
  - name: PyPi TestlinkApiClient
    url: "https://pypi.org/project/TestlinkApiClient/"
  - name: PyPi tm4jReporter
    url: "https://pypi.org/project/tm4jReporter/"
  - name: PyPi opsctl
    url: "https://pypi.org/project/opsctl/"
  - name: PyPi health-menu
    url: "https://pypi.org/project/health-menu/"

beian: 苏ICP备18036961号
