# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: "撩保星球 - Assurance Sphere - 石巍的个人主页"
email: service@bowxeon.com
description: >- # this means to ignore newlines until "baseurl:"
  Assurance Sphere - Will's workspace
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://will.baoxian-sz.com" # the base hostname & protocol for your site, e.g. http://example.com
# twitter_username: jekyllrb
github_username: seoktaehyeon

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

timezone: Asia/Shanghai

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - README.md
  - Dockerfile
  - tool/

css_path: "//bowxeon.gitee.io/www.baoxian-sz.com/assets/css"
js_path: "//bowxeon.gitee.io/www.baoxian-sz.com/assets/js"
img_path: "//vstone.gitee.io/workspace/assets"
post_img_path: "//vstone.gitee.io/workspace/assets/posts"

navs:
  - name: "首页"
    page_title: "撩保星球"
    url: "/"
    target: ""
    has_sub_nav: false
  - name: "软件质量保障"
    page_title: "主题：软件质量保障"
    url: "/tag/软件质量保障"
    target: ""
    has_sub_nav: false
  - name: "软件测试"
    page_title: "主题：软件测试"
    url: "/tag/软件测试"
    target: ""
    has_sub_nav: false
  - name: "DevOps"
    page_title: "主题：DevOps"
    url: "/tag/DevOps"
    target: ""
    has_sub_nav: false
  - name: "工作台"
    page_title: "Will's Workspace"
    url: "/tag/workspace"
    target: ""
    has_sub_nav: false
  - name: "健康保障"
    page_title: "健康保障"
    url: ""
    target: ""
    has_sub_nav: true
    sub_navs:
      - name: "一日菜单"
        page_title: "健康保障"
        url: "/health-menu/day"
        target: "_blank"

my_projects:
  - name: QSphere质量数据平台
    url: "https://qualitysphere.gitee.io/"
  - name: OpenDevOps
    url: "https://qualitysphere.gitee.io/ext/odo/"
  - name: Allure框架中文手册
    url: "https://qualitysphere.gitee.io/ext/allure/"
  - name: PyPi WorkWeixinRobot
    url: "https://pypi.org/project/WorkWeixinRobot/"
  - name: PyPi TestlinkApiClient
    url: "https://pypi.org/project/TestlinkApiClient/"
  - name: PyPi tm4jReporter
    url: "https://pypi.org/project/tm4jReporter/"
  - name: PyPi opsctl
    url: "https://pypi.org/project/opsctl/"
  - name: PyPi
    url: "https://pypi.org/project/health-menu/"

copyright: |
  版权归 <a href="//office.bowxeon.com"><b>真心话险事务所</b></a> 所有<br>
  Copyright ©2017-2021 Truth & Insurance All Rights Reserved
beian: 苏ICP备18036961号